require("ed.plugins-setup")

require("ed.core.options")
require("ed.core.keymaps")
require("ed.core.colorscheme")

require("ed.plugins.comment")
require("ed.plugins.nvim-tree")
require("ed.plugins.lualine")
require("ed.plugins.telescope")
require("ed.plugins.nvim-cmp")
require("ed.plugins.lsp.mason")
require("ed.plugins.lsp.lspsaga")
require("ed.plugins.lsp.lspconfig")
require("ed.plugins.lsp.null-ls")
require("ed.plugins.autopairs")
require("ed.plugins.treesitter")
require("ed.plugins.gitsigns")
